### ISSUE TITLE
新增.env示例文件

### ISSUE THREAD

**Issue by ADKcodeXD** [ADKcodeXD/MMGC-backend#3]
> > $ cross-env NODE_ENV=dev MODE=dev nodemon --watch src -e ts --delay 500ms --exec ts-node -r tsconfig-paths/register src/index.ts --files [nodemon] 2.0.20 [nodemon] to restart at any time, enter `rs` [nodemon] watching path(s): src/**/* [nodemon] watching extensions: ts [nodemon] starting `ts-node -r tsconfig-paths/register src/index.ts --files` [2024-09-06T18:18:33.228] [INFO] default - Your server is running on undefined:undefined [2024-09-06T18:18:33.229] [INFO] default - Click to view http://undefined:undefinedundefined
> > 我也是
> 
> 请查看配置文件

我以为直接跑呢，哈哈！ 有参考么？

_Originally posted by @anyine in https://github.com/ADKcodeXD/MMGC-backend/issues/2#issuecomment-2333753306_

**Comment by anyine** [comment]
> ```
>           > > $ cross-env NODE_ENV=dev MODE=dev nodemon --watch src -e ts --delay 500ms --exec ts-node -r tsconfig-paths/register src/index.ts --files [nodemon] 2.0.20 [nodemon] to restart at any time, enter `rs` [nodemon] watching path(s): src/**/* [nodemon] watching extensions: ts [nodemon] starting `ts-node -r tsconfig-paths/register src/index.ts --files` [2024-09-06T18:18:33.228] [INFO] default - Your server is running on undefined:undefined [2024-09-06T18:18:33.229] [INFO] default - Click to view http://undefined:undefinedundefined
> ```
> 
> > > 我也是
> > 
> > 
> > 请查看配置文件
> 
> 我以为直接跑呢，哈哈！ 有参考么？
> 
> _Originally posted by @anyine in [#2 (comment)](https://github.com/ADKcodeXD/MMGC-backend/issues/2#issuecomment-2333753306)_

我看了一下config里面有好多呢
